### ISSUE TITLE
DynamoDB Configuration

### ISSUE THREAD

**Issue by mchristopher** [coinbase/chainstorage#16]
Would it be possible to get the expected schema/configuration of the 3 DynamoDB tables which store the metadata?

I tried to create them based on the source code, but I think I messed up one of the indexes, and an official guide would be much appreciated!

**Comment by leozc** [comment]
@wangwzhou

**Comment by wangwzhou** [comment]
The DynamoDB related code/implementation is under [storage/metastorage](https://github.com/coinbase/chainstorage/tree/master/internal/storage) directory. 

For DDB tables schema, you can check [block_metadata](https://github.com/coinbase/chainstorage/blob/master/internal/storage/metastorage/model/block_metadata.go#L8) and [block_event](https://github.com/coinbase/chainstorage/blob/master/internal/storage/metastorage/model/block_event.go#L24).
