### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/chainstorage#2]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/chainstorage/compare/35e26ab376efbda7926d04dc104636e03c200e96...1dac23c00b3ef72149962726cf5c33805a846bff) was merged to master by jiezhang.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/chainstorage&ref=1dac23c00b3ef72149962726cf5c33805a846bff)

**Comment by chaoyandy** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for chaoyandy @ 2022-11-23 00:15:32 UTC
User must have write permissions to review

**Comment by chaoyandy** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for chaoyandy @ 2022-11-23 00:37:57 UTC
User must have write permissions to review

**Comment by chaoyandy** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for chaoyandy @ 2022-11-23 00:59:24 UTC
User must have write permissions to review

**Comment by wangwzhou** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for wangwzhou @ 2022-11-23 01:28:56 UTC
User must have write permissions to review

**Comment by chaoyandy** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for chaoyandy @ 2022-11-23 02:01:59 UTC
User must have write permissions to review

**Comment by cb-heimdall** [comment]
Review Error for wangwzhou @ 2022-11-23 02:07:59 UTC
User must have write permissions to review

**Comment by chaoyandy** [comment]
👍

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
chaoyandy | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/chainstorage&ref=1dac23c00b3ef72149962726cf5c33805a846bff)

**Comment by wangwzhou** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for wangwzhou @ 2022-11-23 17:25:28 UTC
User must have write permissions to review

**Comment by wangwzhou** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for wangwzhou @ 2022-12-06 00:35:52 UTC
User must have write permissions to review

**Comment by wangwzhou** [comment]
👍
