### ISSUE TITLE
Provide bypass for confirmation

### ISSUE THREAD

**Issue by mchristopher** [coinbase/chainstorage#23]
We're working on automating deployment of ChainStorage on AWS, and I'm running into an issue with starting workflows.

There is currently no way to bypass the "Are you sure you want to start XXX" message in the admin CLI. I would love to be able to pass `--confirm` or set an environment variable so that no CLI interaction is required to start the workflows.

**Comment by leozc** [comment]
Please feel free to send a pull request - @jiezhang

**Comment by leozc** [comment]
@mchristopher I would close this ticket for now, please feel free to reopen if you want to revisit.
