### ISSUE TITLE
ChainStorage workflow ergonomic

### ISSUE THREAD

**Issue by leozc** [coinbase/chainstorage#34]
ChainStorage is reliant on Temporal, which is a crucial dependency. However, it currently operates on an outdated version of Temporal. Even the current Temporal UI Docker is no longer supported. 

It would be advisable to modify ChainStorage so that it can operate on a readily available Temporal deployment.

**Comment by bestmike007** [comment]
I've already upgraded the docker images for running temporal and the ui. It doesn't seem to have any compatibility issues.

However, there are breaking changes in temporal sdk, which might take some time.

**Comment by leozc** [comment]
Sure I can drop this then
