### ISSUE TITLE
No such file go-bindata

### ISSUE THREAD

**Issue by sanchitram1** [coinbase/chainstorage#8]
Was able to run until bootstrap, but when trying to `make build`, got an error saying that there is No such file or directory.  I also got the same error when executing as individual lines:
`go run ./tools/config_gen ./config_templates/config .` -- ran successfully
`go-bindata -ignore secrets\.yml -ignore config/config.go -modtime 1640048354 -o config/config.go -pkg config config/..` -- failed

Error message:
```
make: go-bindata: No such file or directory
make: *** [config] Error 1
```

My guess is `go-bindata` is not where it's supposed to be?

**Comment by Theholycitywebproject** [comment]
Also having this problem

**Comment by leozc** [comment]
Please try to run the scripts/bootstrap.sh

**Comment by leozc** [comment]
resolved
