### ISSUE TITLE
Launchpad Rest API Key Application

### ISSUE THREAD

**Issue by bestmike007** [coinbase/chainstorage#92]
Hi there,

I'm currently working on a workflow (https://github.com/coinbase/chainstorage/pull/91) which replicate block data from another chainstorage.
Is there a way to apply for a launchpad api key (mentioned in the notion doc), so that I can test it?

**Comment by zhanwux** [comment]
Thank you for reaching out. I created an new API key for external testing purpose.
What's your email that I can share the key to?

**Comment by bestmike007** [comment]
Thank you @zhanwux 

bestmike007@users.noreply.github.com

**Comment by bestmike007** [comment]
@zhanwux sorry the previous one doesn't work.

i@bestmike007.com
