### ISSUE TITLE
help wanted on correct procedure for deployment

### ISSUE THREAD

**Issue by joshuasu-async** [coinbase/chainstorage#93]
First of all, huge thanks to all the contributors! Really appreciate all the work here.

I am trying to use this project to ingest a blockchain, for example, ethereum-mainnet. I have done the following steps:

1. set up AWS resources, DynamoDB tables, S3 bucket, and SQS queue.
2. set up a temporal instance.
3. update the config-template accordingly, and generate the config files.
4. I can successfully run the following command: 
 `go run ./cmd/admin workflow start --workflow backfiller --input '{"StartHeight": 11000000, "EndHeight": 11000010, "NumConcurrentExtractors": 24}' --blockchain ethereum --network mainnet --env production`
and I can verify that the data has been stored in the S3 bucket, block_table also have correct entries.

At this point, my understanding is that I manually backfill once by running the above command, then I should set up the poller by run the containers defined in docker-compose.yml. However, the cron service always throws error.

I also have trouble running other workflows, such as monitor, event_backfiller and poller.

Can anyone provide help to elaborate on how this project is supposed to be used? I have a hard time understanding the intentions from the readme doc. Thanks in advance!

**Comment by leozc** [comment]
Possible to show the errors from the cron?

We use temporal as the workflow engine (as you can see from the docker, there is even an UI for that), all actions taken against Chainstorage data plate is through the workflow

**Comment by joshuasu-async** [comment]
> Possible to show the errors from the cron?
> 
> We use temporal as the workflow engine (as you can see from the docker, there is even an UI for that), all actions taken against Chainstorage data plate is through the workflow

Thank you very much for the reply, Leo!

Here is the logs when I run `CHAINSTORAGE_ENVIRONMENT=production go run ./cmd/cron`:

`{"level":"info","ts":1708490042.5115578,"caller":"sqs/dlq.go:303","msg":"initialized dlq","package":"sqs","storage_type":"sqs","url":"https://sqs.us-west-1.amazonaws.com/xxxxxxxxxxxx/chainstorage_blocks_ethereum_mainnet_dlq","config":{"Name":"chainstorage_blocks_ethereum_mainnet_dlq","VisibilityTimeoutSecs":600,"DelaySecs":900,"OwnerAccountId":""}}

{"level":"info","ts":1708490042.802547,"caller":"cron/job.go:56","msg":"delay start","package":"cron","duration":"0s"}
{"level":"info","ts":1708490042.802561,"caller":"cron/job.go:56","msg":"delay start","package":"cron","duration":"0s"}
{"level":"info","ts":1708490042.802596,"caller":"cron/job.go:56","msg":"delay start","package":"cron","duration":"0s"}
{"level":"info","ts":1708490042.8026009,"caller":"cron/job.go:56","msg":"delay start","package":"cron","duration":"10m0s"}
{"level":"info","ts":1708490042.802608,"caller":"cron/job.go:56","msg":"delay start","package":"cron","duration":"10m0s"}
{"level":"info","ts":1708490042.802604,"caller":"cron/runner.go:41","msg":"starting cron","package":"cron","num_jobs":5}
{"level":"info","ts":1708490042.8026721,"caller":"cron/main.go:77","msg":"started cron"}
{"level":"info","ts":1708490043.067342,"caller":"cron/dlq_processor.go:80","msg":"dlq is empty","package":"cron"}
{"level":"info","ts":1708490044.0706408,"caller":"cron/dlq_processor.go:80","msg":"dlq is empty","package":"cron"}
{"level":"info","ts":1708490045.073047,"caller":"cron/dlq_processor.go:80","msg":"dlq is empty","package":"cron"}
{"level":"info","ts":1708490046.0679,"caller":"cron/dlq_processor.go:80","msg":"dlq is empty","package":"cron"}
{"level":"info","ts":1708490047.072434,"caller":"cron/dlq_processor.go:80","msg":"dlq is empty","package":"cron"}
{"level":"warn","ts":1708490047.099319,"caller":"retry/retry.go:170","msg":"encountered a retryable error","package":"jsonrpc","attempts":1,"error":"failed to make http request (method=&{eth_blockNumber 5s}, params=[], endpoint=eth-rpc-nodes-erigon-prysm-round-robin): RetryableError: failed to send http request: context canceled","errorVerbose":"failed to make http request (method=&{eth_blockNumber 5s}, params=[], endpoint=eth-rpc-nodes-erigon-prysm-round-robin):\n    github.com/coinbase/chainstorage/internal/blockchain/jsonrpc.(*clientImpl).Call.func1\n        /Users/joshuasu/code/chainstorage/internal/blockchain/jsonrpc/client.go:194\n  - RetryableError: failed to send http request: context canceled"}
{"level":"warn","ts":1708490047.099311,"caller":"retry/retry.go:170","msg":"encountered a retryable error","package":"jsonrpc","attempts":1,"error":"failed to make http request (method=&{eth_blockNumber 5s}, params=[], endpoint=eth-rpc-nodes-erigon-prysm-sticky): RetryableError: failed to send http request: context canceled","errorVerbose":"failed to make http request (method=&{eth_blockNumber 5s}, params=[], endpoint=eth-rpc-nodes-erigon-prysm-sticky):\n    github.com/coinbase/chainstorage/internal/blockchain/jsonrpc.(*clientImpl).Call.func1\n        /Users/joshuasu/code/chainstorage/internal/blockchain/jsonrpc/client.go:194\n  - RetryableError: failed to send http request: context canceled"}
{"level":"warn","ts":1708490047.0994902,"caller":"instrument/instrument.go:253","msg":"jsonrpc.request","package":"jsonrpc","method":"eth_blockNumber","endpoint":"eth-rpc-nodes-erigon-prysm-sticky","numParams":1,"params":[null],"duration":"98.7175ms","error":"context canceled"}
{"level":"warn","ts":1708490047.099345,"caller":"retry/retry.go:170","msg":"encountered a retryable error","package":"jsonrpc","attempts":1,"error":"failed to make http request (method=&{eth_blockNumber 5s}, params=[], endpoint=eth-rpc-nodes-erigon-prysm-round-robin): RetryableError: failed to send http request: context canceled","errorVerbose":"failed to make http request (method=&{eth_blockNumber 5s}, params=[], endpoint=eth-rpc-nodes-erigon-prysm-round-robin):\n    github.com/coinbase/chainstorage/internal/blockchain/jsonrpc.(*clientImpl).Call.func1\n        /Users/joshuasu/code/chainstorage/internal/blockchain/jsonrpc/client.go:194\n  - RetryableError: failed to send http request: context canceled"}
{"level":"warn","ts":1708490047.099555,"caller":"instrument/instrument.go:253","msg":"jsonrpc.request","package":"jsonrpc","method":"eth_blockNumber","endpoint":"eth-rpc-nodes-erigon-prysm-round-robin","numParams":1,"params":[null],"duration":"98.724167ms","error":"context canceled"}
{"level":"warn","ts":1708490047.099445,"caller":"instrument/instrument.go:253","msg":"jsonrpc.request","package":"jsonrpc","method":"eth_blockNumber","endpoint":"eth-rpc-nodes-erigon-prysm-round-robin","numParams":1,"params":[null],"duration":"98.614166ms","error":"context canceled"}
{"level":"warn","ts":1708490047.099565,"caller":"instrument/instrument.go:253","msg":"client.get_latest_height","package":"client","endpoint_group":"consensus","duration":"98.946667ms","error":"failed to call eth_blockNumber: context canceled","errorVerbose":"failed to call eth_blockNumber:\n    github.com/coinbase/chainstorage/internal/blockchain/client/ethereum.(*EthereumClient).GetLatestHeight\n        /Users/joshuasu/code/chainstorage/internal/blockchain/client/ethereum/ethereum.go:1180\n  - context canceled"}
{"level":"warn","ts":1708490047.0995798,"caller":"instrument/instrument.go:253","msg":"client.get_latest_height","package":"client","endpoint_group":"slave","duration":"98.9735ms","error":"failed to call eth_blockNumber: context canceled","errorVerbose":"failed to call eth_blockNumber:\n    github.com/coinbase/chainstorage/internal/blockchain/client/ethereum.(*EthereumClient).GetLatestHeight\n        /Users/joshuasu/code/chainstorage/internal/blockchain/client/ethereum/ethereum.go:1180\n  - context canceled"}
{"level":"info","ts":1708490047.099623,"caller":"instrument/instrument.go:247","msg":"node.health_check","package":"cron","health_check_type":"slave_primary_health_check","duration":"99.024458ms","error":"failed to ping slave: failed to call eth_blockNumber: context canceled","errorVerbose":"failed to ping slave:\n    github.com/coinbase/chainstorage/internal/cron.(*nodeCanaryTask).Run.func3.1\n        /Users/joshuasu/code/chainstorage/internal/cron/node_canary.go:358\n  - failed to call eth_blockNumber:\n    github.com/coinbase/chainstorage/internal/blockchain/client/ethereum.(*EthereumClient).GetLatestHeight\n        /Users/joshuasu/code/chainstorage/internal/blockchain/client/ethereum/ethereum.go:1180\n  - context canceled"}
{"level":"warn","ts":1708490047.099505,"caller":"instrument/instrument.go:253","msg":"client.get_latest_height","package":"client","endpoint_group":"master","duration":"98.927625ms","error":"failed to call eth_blockNumber: context canceled","errorVerbose":"failed to call eth_blockNumber:\n    github.com/coinbase/chainstorage/internal/blockchain/client/ethereum.(*EthereumClient).GetLatestHeight\n        /Users/joshuasu/code/chainstorage/internal/blockchain/client/ethereum/ethereum.go:1180\n  - context canceled"}
{"level":"info","ts":1708490047.099691,"caller":"instrument/instrument.go:247","msg":"node.health_check","package":"cron","health_check_type":"master_primary_health_check","duration":"99.114667ms","error":"failed to ping master: failed to call eth_blockNumber: context canceled","errorVerbose":"failed to ping master:\n    github.com/coinbase/chainstorage/internal/cron.(*nodeCanaryTask).Run.func2.1\n        /Users/joshuasu/code/chainstorage/internal/cron/node_canary.go:301\n  - failed to call eth_blockNumber:\n    github.com/coinbase/chainstorage/internal/blockchain/client/ethereum.(*EthereumClient).GetLatestHeight\n        /Users/joshuasu/code/chainstorage/internal/blockchain/client/ethereum/ethereum.go:1180\n  - context canceled"}
{"level":"info","ts":1708490047.099593,"caller":"instrument/instrument.go:247","msg":"node.health_check","package":"cron","health_check_type":"consensus_primary_health_check","duration":"98.98075ms","error":"failed to ping consensus: failed to call eth_blockNumber: context canceled","errorVerbose":"failed to ping consensus:\n    github.com/coinbase/chainstorage/internal/cron.(*nodeCanaryTask).Run.func5.1\n        /Users/joshuasu/code/chainstorage/internal/cron/node_canary.go:450\n  - failed to call eth_blockNumber:\n    github.com/coinbase/chainstorage/internal/blockchain/client/ethereum.(*EthereumClient).GetLatestHeight\n        /Users/joshuasu/code/chainstorage/internal/blockchain/client/ethereum/ethereum.go:1180\n  - context canceled"}
{"level":"warn","ts":1708490047.099803,"caller":"instrument/instrument.go:253","msg":"cron.job","package":"cron","task":"node_canary","duration":"99.365334ms","error":"failed to finish node canary task: failed to get max event id from storage: no event history","errorVerbose":"failed to finish node canary task:\n    github.com/coinbase/chainstorage/internal/cron.(*nodeCanaryTask).Run\n        /Users/joshuasu/code/chainstorage/internal/cron/node_canary.go:590\n  - failed to get max event id from storage:\n    github.com/coinbase/chainstorage/internal/cron.(*nodeCanaryTask).Run.func1\n        /Users/joshuasu/code/chainstorage/internal/cron/node_canary.go:284\n  - no event history:\n    github.com/coinbase/chainstorage/internal/storage/internal/errors.init\n        /Users/joshuasu/code/chainstorage/internal/storage/internal/errors/error.go:12"}`


There are two types of error:
1.  "context canceled" when calling eth_blockNumber;
2. "failed to finish node canary task: failed to get max event id from storage: no event history"

I have no idea why the first type error pops up, since running the `./cmd/admin backfill` has no issues. I guess it may be a result of the second type error?
For the the second type error, I thought I may need to backfill the events by running `CHAINSTORAGE_ENVIRONMENT=production go run ./cmd/admin workflow start --workflow event_backfiller --input '{"StartSequence": 1, "EndSequence": 1000, "UpgradeFromEventTag": 2}' --blockchain ethereum --network mainnet --env production`. But I am not sure that input I am supposed to put here. Therefore, if anyone can elaborate on the developer workflow to run this project, it will be really helpful!

Thank you very much!

**Comment by leozc** [comment]
eth-rpc-nodes-erigon-prysm-sticky
^^ are you using erigon node? We have only tested GEth 

Cc @jiezhang

**Comment by HenryYYang** [comment]
For your input, you should have `"UpdateWatermark ": true` so that the backfill workflow will update the watermark.  I think this will resolve issue 1.
After that, you need to run the streamer to generate the event table, which should resolve issue 2.

**Comment by joshuasu-async** [comment]
To summarize, to ingest a chain, here is what the developer needs to do:
1. set up AWS resources;
2. generate config files;
3. run backfiller workflow once (with updateWatermark = true);
4. start streamer workflow;
5. start poller workflow.

**Comment by leozc** [comment]
@joshuasu-async has the problem resovled?

**Comment by joshuasu-async** [comment]
yes, thanks!
